### ISSUE TITLE
Question: How can I add new API support?

### ISSUE THREAD

**Issue by MSakamaki** [amilajack/eslint-plugin-compat#106]
I It is helped by this wonderful tool.

checking [URLSearchParams](https://caniuse.com/#search=urlsearchparams) and [URL API](https://caniuse.com/#search=URL) that are used simultaneously with `fetch API` is not done.

Is it a right way to contribute by adding a setting to `CanIUseProvider` of` ./lib/providers/CanIUseProvider.js` and throwing a pull requiest?

Please tell me if there is a better way to contribute to other.

**Comment by amilajack** [comment]
Yup, that's the way to go

**Comment by kenju** [comment]
@amilajack I suppose you can close this PR ?
