### ISSUE TITLE
Edge, IE and Electron does not support .x and .y on getBoundingClientRect

### ISSUE THREAD

**Issue by enjikaka** [amilajack/eslint-plugin-compat#108]
Can we have a check for that? :)

**Comment by kenju** [comment]
@enjikaka 

Hi, I'm just a passer-by.

If you want to add a new rule, currently it is supposed to add a new rule at `providers/CanIUseProvider.js` with a test.
see my PR as an example 👍 

https://github.com/amilajack/eslint-plugin-compat/pull/115

**Comment by amilajack** [comment]
This plugin does not support instance methods at the moment. See https://github.com/amilajack/eslint-plugin-compat/issues/168#issuecomment-462009281
