### ISSUE TITLE
Update to browserslist 3

### ISSUE THREAD

**Issue by ismay** [amilajack/eslint-plugin-compat#112]
Just a reminder that this project uses `"browserslist": "^2.11.3"`. Would be nice to be able to use it with browserslist 3.

Otherwise this plugin will break when using the `not dead` query from v3 for example.

**Comment by amilajack** [comment]
Would love a PR for this

**Comment by ismay** [comment]
If I have some extra time I’ll definitely open one 👌. If anyone else wants to help out in the meantime, please do 😊!

**Comment by ismay** [comment]
PR submitted.
