### ISSUE TITLE
ESLint v5 Compatibility

### ISSUE THREAD

**Issue by bjankord** [amilajack/eslint-plugin-compat#120]
Curious, is this plugin compatible with ESLint v5?

**Comment by rsturim** [comment]
When I attempt to install eslint-plugin-compat with eslint@5.0.1 I get this error

`npm ERR! peerinvalid Peer eslint-plugin-compat@2.5.0 wants eslint@^3.0.0 || ^4.0.0`

is it possible that this line is invalid syntax? 

`"eslint": "^3.0.0 || ^4.0.0 || ^5.0.0"`

**Comment by amilajack** [comment]
See [package.json#L71](https://github.com/amilajack/eslint-plugin-compat/blob/master/package.json#L71)

**Comment by ljharb** [comment]
The published package is wrong: 
https://unpkg.com/eslint-plugin-compat@2.5.0/package.json

**Comment by amilajack** [comment]
Fixed this in `v2.5.1`
