### ISSUE TITLE
How to override settings.browser?

### ISSUE THREAD

**Issue by voxpelli** [amilajack/eslint-plugin-compat#125]
This may not really be a question for this project but perhaps for the main ESLint project instead, but I'm right now working with a shared config that uses `eslint-plugin-compat`, and that shared config sets a `settings.browsers` value to a certain list of browsers.

My problem is this: I want to revert that in my project as my project properly implements a browserslist setting, but I can't figure out what to add:

```json
{
  "extends": "@prefix/eslint-config-shared",
  "root": true,
  "settings": {
    "browsers": false
  }
}
```

Does not work, it just replaces the first value in the shared `settings.browsers` with `false` – and setting `null` gives another error.

Any suggestions on how to achieve this?

**Comment by amilajack** [comment]
@voxpelli sorry for the late response. You could try this:

```jsonc
// root config:
{
  "extends": [
    "extends": ["plugin:compat/recommended"]
  ],
  "root": true,
  "rules": {
    "compat/compat": ["error", "defaults, not ie < 9"]
  }
}
```

Other config
```jsonc
{
  "@prefix/eslint-config-shared",
  "rules": {
    "compat/compat": "error"
  }
}
```
