### ISSUE TITLE
Prototype pollution attack vulnerability

### ISSUE THREAD

**Issue by GreenGremlin** [amilajack/eslint-plugin-compat#129]
The current release of eslint-plugin-compat on npm (2.5.1) has a [prototype pollution attack vulnerability](https://hackerone.com/reports/381185), through its dependency on `mdn-browser-compat-data@0.0.40` > `extend@3.0.1`.

[A recent commit](https://github.com/amilajack/eslint-plugin-compat/commit/675b78b8e2373223c9e50758be6d757440a9b6e4) appears to have resolved the vulnerability, it just needs to be published to npm.

**Comment by amilajack** [comment]
Missed this. Thanks of noting this. I'll publish a new version in a few minutes

**Comment by GreenGremlin** [comment]
> Missed this. Thanks of noting this. I'll publish a new version in a few minutes

Thanks!

**Comment by amilajack** [comment]
Just pushed to `eslint-plugin-compat@next`. Would appreciate it if you could test it out before i publish

**Comment by GreenGremlin** [comment]
Sorry, apparently I was wrong. Mdn-browser-compat-data is still pinned to `extend@3.0.1`. I filed [an issue](https://github.com/mdn/browser-compat-data/issues/2915) and [PR](https://github.com/mdn/browser-compat-data/pull/2916) with them to fix it.

**Comment by GreenGremlin** [comment]
This issue should still be open. The fix was just published in mdn-browser-compat-data v0.0.53. I'll put up a PR to update the version pin.

**Comment by vikr01** [comment]
Seems to have been resolved in #135. Thanks @GreenGremlin!
