### ISSUE TITLE
console.log method left in latest release by accident

### ISSUE THREAD

**Issue by niftylettuce** [amilajack/eslint-plugin-compat#132]
please remove this line https://github.com/amilajack/eslint-plugin-compat/commit/258055240e0e199c4088fc5aa63c2d4b6053e996#diff-9a185028cbfd9bdba4e90474c6878f27R10 and then publish new version, add deprecation notice the bad version with console.log artifact

cc @amilajack

**Comment by amilajack** [comment]
Oh wow how did I miss that. Thanks for catching this! Fixed in `2.6.1`

**Comment by niftylettuce** [comment]
no problem at all, thank you ❤️
