### ISSUE TITLE
Can't get eslint plugin eslint-plugin-compat to work

### ISSUE THREAD

**Issue by devinrhode2** [amilajack/eslint-plugin-compat#152]
Felt like this is more appropriate for stackoverflow, but, not sure anybody knows the answer to it. (I never get stuck on things like this, maybe there's some underlying issue with my toolchain, which is extremely basic and simple btw)

https://stackoverflow.com/questions/53526978/cant-get-eslint-plugin-eslint-plugin-compat-to-work

**Comment by vikr01** [comment]
Even if you've linked it on stackoverflow, could you also repost/quote the problem here?

**Comment by amilajack** [comment]
@devinrhode2 Please create a repo that reproduces this issue and link it here
