### ISSUE TITLE
Doesn't detect that `.includes` is not supported

### ISSUE THREAD

**Issue by Kriostak** [amilajack/eslint-plugin-compat#168]
Hi. At current moment plugin doesn't see that "includes" doesn't work for IE11.

`"browserslist": [
       "last 2 versions",
       "not ie <= 10"
  ]`

https://caniuse.com/#search=includes
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/includes

In any case thanks for your work about this plugin. It helps me a lot. )

**Comment by amilajack** [comment]
Instance methods are difficult to check because types need to be known at runtime. For example, `foo.includes` might not be an array so it isn't safe to error.

**Comment by niftylettuce** [comment]
Could we error anyways?  By not throwing an error at all we assume the compiled code is lint-free, but when run in an older environment exceptions are thrown due to missing methods.

**Comment by ljharb** [comment]
@niftylettuce you can use `no-restricted-properties` to block any usage of `.includes` if you want.

**Comment by niftylettuce** [comment]
The same issue occurs for methods like `.append` and `.replaceWith` (e.g. `document.body.append` and `document.body.replaceWith` for IE Edge 13-16.  Should we re-open @ljharb?  I def think this should be reported - usually the only way people catch these issues is by capturing them in client-side logs as I just did.

Ref:
* https://caniuse.com/#feat=dom-manip-convenience
* https://github.com/WebReflection/dom4
* https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.append%2CElement.prototype.prepend%2CElement.prototype.replaceWith%2CElement%2CElement.prototype.after%2CElement.prototype.before%2CElement.prototype.cloneNode%2CElement.prototype.classList%2CElement.prototype.matches%2CElement.prototype.dataset%2CElement.prototype.closest%2CElement.prototype.placeholder%2CElement.prototype.remove%2CElement.prototype.toggleAttribute

**Comment by lukejagodzinski** [comment]
@amilajack what about instance methods when @typescript-eslint is being used? Does the AST contain information about types then?

**Comment by lifeiscontent** [comment]
@amilajack ESLint provides type information of the code running, why wouldn't you be able to do this?

**Comment by amilajack** [comment]
@lifeiscontent For the following example, where would the types be?

https://astexplorer.net/#/gist/60a8711f2a505ccdcd60a76045114925/d7a96f6663b617216b7189d0c2a624b82d5b897d

**Comment by lifeiscontent** [comment]
@amilajack `type: Literal` and `value: 123`. if it's a literal and it is typeof === "string" then it supports includes.

**Comment by eightHundreds** [comment]
eslint-plugin-builtin-compat
