### ISSUE TITLE
infra: migrate to azure pipelines

### ISSUE THREAD

**Issue by amilajack** [amilajack/eslint-plugin-compat#183]
* We can migrate away from `appveyor`, which is incredibly slow
* One CI instead of two
* Much faster than appveyor and travis

We can easily use [the azure config from eslint-plugin-flowtype-errors](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/azure-pipelines.yml)

**Comment by ljharb** [comment]
travis  runs windows now, so you could just use that?

**Comment by amilajack** [comment]
Travis windows is still in beta. I've also used travis windows and its still very buggy. Also azure pipelines tests run much faster and are easier to find errors in because the builds are divided into different stages and you can see exactly what stage failed.
