### ISSUE TITLE
Override Browser List on Directory Basis?

### ISSUE THREAD

**Issue by matthewwithanm** [amilajack/eslint-plugin-compat#189]
Because the browserslist is defined in `package.json`, there doesn't seem to be a way to override it for subdirectories. Is this right? #121 looks promising but there hasn't been movement on it for a while.

Thanks for the help!

**Comment by ljharb** [comment]
When would you have two different sets of supported browsers in dirs in the same repo?

**Comment by matthewwithanm** [comment]
One reason is for service workers. Since you'll only run them in browsers that support them, they may have more APIs available than the main app which has to work regardless of service worker support.

**Comment by ljharb** [comment]
Can you add a nested package.json in those dirs?

**Comment by matthewwithanm** [comment]
It's possible to have a completely separate project that just happens to be inside of my current project but I'm looking to get all of my lint results from one call to eslint (and in the IDE). This means customizing the behavior for certain files or directories (which is normally not a problem with eslint).

**Comment by ljharb** [comment]
I’d expect a nested package.json to work. Does it not?

**Comment by matthewwithanm** [comment]
No 😔. My guess is that it just reads the package.json once based on the root, not each file (but I haven't verified).

**Comment by amilajack** [comment]
@matthewwithanm https://github.com/amilajack/eslint-plugin-compat/issues/189 Might resolve this

**Comment by matthewwithanm** [comment]
You mean #217? ☺️

**Comment by amilajack** [comment]
oh haha yea that. Let me know if this resolves the issue you were running into.

**Comment by amilajack** [comment]
Closing this because this was resolved
