### ISSUE TITLE
"Set/Map is not supported in ..." when using set/map from immutable.js in v3

### ISSUE THREAD

**Issue by thomas88** [amilajack/eslint-plugin-compat#192]
After updating to v3, I'm getting `Set is not supported in ...` when using `Set` from immutable.js, i.e.

```javascript
import { Set } from 'immutable';

const mySet = Set([]); // lint issue here
```

**Comment by amilajack** [comment]
@thomas88 Can you please test out `eslint-plugin-compat@next` and see if this resolves this bug for you? You can try it out by running the following:
```bash
# NPM
npm i --save-dev eslint-plugin-compat@next
# Yarn
yarn add --dev eslint-plugin-compat@next
```
Thanks!

**Comment by thomas88** [comment]
Yes, this resolves the issue. Thanks for the quick fix @amilajack!
