### ISSUE TITLE
Without `polyfills` for `fetch`, getting error

### ISSUE THREAD

**Issue by brettz9** [amilajack/eslint-plugin-compat#223]
Just including `fetch()` in a file is enough to cause the ESLint error, "Cannot read property '6.17.0' of undefined.", though the error disappears once I add `"fetch"` to `settings`->`polyfills`.

Searching through my entire project, the only two files with this version number are in:

1. `node-releases/data/processed/envs.json`
2. `node-releases/data/raw/nodejs.json`

**Comment by amilajack** [comment]
Can you please create a repository that reproduces this. That would really help me debug this.

**Comment by brettz9** [comment]
You can clone https://github.com/brettz9/mw-replace-bot and get rid of settings->polyfills->fetch --and if you wish, change "extends" in `.eslintrc.js` from my config `"eslint-config-ash-nazg"` (which includes compat) to `"plugin:compat/recommended"`.

**Comment by brettz9** [comment]
Sorry, neglected to mention a triggering file: `gui/gui-index.js`, but again, even just `fetch()` alone will do the trick... And the repo is pretty light as it is...

**Comment by brettz9** [comment]
It appears I was mistakenly assuming that the `browserslist` support would allow use of "Node" as a browser type for compatibility checking.

**Comment by JounQin** [comment]
Should be same as https://github.com/amilajack/eslint-plugin-compat/issues/26.

**Comment by brettz9** [comment]
No, the issue I am reporting on here is simply a bug with handling browser APIs when one has "Node" as an item within `browserslist`. While this repo merely describes itself as being for browsers, the `browserslist` spec allows for "Node" as a value as well, but this library is choking on it. Also I wonder whether this library might support Node in the future as it already seems to have a goal to support Kangax which tracks Nodes support (though I guess this may cover the same ground as `eslint-plugin-node`). In any case, I'd expect some better error message if browserslist doesn't include one of the expected types.

**Comment by JounQin** [comment]
My issue is also caused by `current  node` query.

**Comment by brettz9** [comment]
Oh, ok, I see you've since edited the issue number. Gotcha.

**Comment by amilajack** [comment]
This issue was fixed a while ago.
