### ISSUE TITLE
Why is Node v8.x required? 

### ISSUE THREAD

**Issue by niftylettuce** [amilajack/eslint-plugin-compat#224]
https://github.com/amilajack/eslint-plugin-compat/blob/master/package.json#L70

**Comment by ljharb** [comment]
it was done in #218, presumably to be able to transpile to a later target.

**Comment by amilajack** [comment]
It's not really required. As a maintainer I didn't want to handle bug reports for older versions. But if you need support for older versions I'll lower the node version requirement. Should be as simple as a babel-preset-env target change

**Comment by niftylettuce** [comment]
If we could remove the requirement in `engine` of `package.json` that would be great

**Comment by ljharb** [comment]
eslint itself requires node 4, and babel 7 requires node 4 as well i think - so removing it isn't an option, but dropping it down to 4 should be.

**Comment by niftylettuce** [comment]
Makes sense, ty for lmk

**Comment by amilajack** [comment]
Yarn supports >=8 so we're locked to that same semver because of users who install this lib with yarn

**Comment by ljharb** [comment]
Um, that’s not how it works - npm users aren’t locked to that, and older versions of yarn won’t require node 8.

An eslint plugin should always support every node version eslint supports.

**Comment by amilajack** [comment]
[Semver package requires node >=10](https://dev.azure.com/amilajack/amilajack/_build/results?buildId=8426&view=logs&j=acaaecd7-9fab-5554-0baf-fc904fde88ac&t=af29adf3-9a05-5d41-c8d7-012c89f578eb)

**Comment by ljharb** [comment]
The latest version does, but there’s no reason we need to use > v6 - v7 only changes prerelease logic.

Let’s stop looking for excuses to drop support, and try to support as far back as possible?
