### ISSUE TITLE
Not showing errors for arrow functions

### ISSUE THREAD

**Issue by Glinkis** [amilajack/eslint-plugin-compat#232]
No error is shown for `const fn = () => {}` when set to `ie >= 11`, which doesnt support arrow functions.

**Comment by ljharb** [comment]
That's not API; you should set your eslint parserOptions ecmaVersion so that arrow functions won't parse, and then you get a syntax error.

(or, use babel with babel-preset-env)

**Comment by Glinkis** [comment]
Ah, sorry then, my bad.
