### ISSUE TITLE
browserlist/babel-preset-env config sharing

### ISSUE THREAD

**Issue by jacobmischka** [amilajack/eslint-plugin-compat#24]
The readme mentions specifying target versions in the config, but doing that doesn't seem to work. `"ie 9"` and `"ie >= 9"` both break eslint, `"ie"` itself works fine.

Output:
```
TypeError: Cannot convert undefined or null to object
    at /home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:100:47
    at Array.filter (native)
    at getUnsupportedTargets (/home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:99:20)
    at Object.isValid (/home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:87:12)
    at /home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/Lint.js:57:20
    at Array.find (native)
    at Lint (/home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/Lint.js:56:6)
    at EventEmitter.lint (/home/mischka/projects/residentprogram/node_modules/eslint-plugin-compat/lib/rules/compat.js:49:40)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Thanks, this is a super neat idea, really excited for it.

**Comment by amilajack** [comment]
Those were meant to be examples of what to expect. I haven't written the functionality for that yet. I'll finish that by today. Sorry for the confusion

**Comment by jacobmischka** [comment]
Oh okay, no worries! Thank you!

**Comment by bdougherty** [comment]
Would be great to support https://github.com/ai/browserslist so the list can be shared with other tools!

**Comment by amilajack** [comment]
Yup! That's planned for release 3.0.0: https://github.com/amilajack/eslint-plugin-compat/wiki#release-300-babelbrowserlist-integration

**Comment by bfred-it** [comment]
I think `browserlist` actually already covers what you have in that v2.0 list. No need to reinvent the wheel

**Comment by amilajack** [comment]
@bfred-it good idea. I'll add browserlist versioning in release 2.0.0.

**Comment by amilajack** [comment]
Decided that 1.0.0 should be the release with `browserslist` support. Also I just released `1.0.0` 🎉

**Comment by bfred-it** [comment]
FYI the browserlist file is also automatically supported, not just the package.json file like the new readme mentions 👍  🙂

**Comment by amilajack** [comment]
Yea, i should add that to the readme

**Comment by mozmorris** [comment]
@amilajack what's the score with attempting to support `babel-preset-env`. Is this still on the roadmap?

**Comment by amilajack** [comment]
@mozmorris I'm somewhat reluctant to support it. I think using the `browserslist` config in the `package.json` would be a better alternative. Thoughts on this?

**Comment by jacobmischka** [comment]
I agree, the browserslist pseudo-standard would be better than reading any dedicated babel config.

**Comment by mozmorris** [comment]
@amilajack of course and I know you were involved with the discussion around this topic over on `babel-preset-env`. If using browserslist config in package.json drops over there, this discussion could well be moot.

In my head I was thinking of a fallback approach. If the developer had no explicit browserslist config in their package.json, it would detect their preset-env config.

Let's compare the two configs we currently have _(shots taken from docs)_:

`.babelrc`
<img width="405" alt="screen shot 2017-03-11 at 08 24 53" src="https://cloud.githubusercontent.com/assets/156303/23821813/e58389e8-0635-11e7-8ad1-77d6270a80c6.png">

`package.json`
<img width="426" alt="screen shot 2017-03-11 at 08 25 10" src="https://cloud.githubusercontent.com/assets/156303/23821823/0de0aa88-0636-11e7-9c83-48519d88695a.png">

Clearly there's some duplication happening here.
