### ISSUE TITLE
Add Eslint 6 in peerDependencies

### ISSUE THREAD

**Issue by jimblue** [amilajack/eslint-plugin-compat#242]
Hi,

**ESlint 6** have been release, could you please add it to the **peerDependencies**, thank you.

https://github.com/amilajack/eslint-plugin-compat/blob/5079a8d14865928552093dee3d2bb2e49fb3df74/package.json#L67

**Comment by amilajack** [comment]
Closed in https://github.com/amilajack/eslint-plugin-compat/pull/243
