### ISSUE TITLE
eslint-plugin-compat doesn't work on ESLint v6.0.0

### ISSUE THREAD

**Issue by laukstein** [amilajack/eslint-plugin-compat#244]
After ESLint update to v6.0.0 https://github.com/eslint/eslint/releases/tag/v6.0.0, eslint-plugin-compat is no longer working, shows :

     Error     24,24: Promise is not supported in IE 11 (compat/compat)
     Error     66,24: Promise.reject() is not supported in IE 11 (compat/compat)
     Error     85,25: URLSearchParams is not supported in IE 11 (compat/compat)
     Error    118,36: Promise is not supported in IE 11 (compat/compat)
     Error    139,20: Promise.reject() is not supported in IE 11 (compat/compat)
     Error    147,26: URL is not supported in IE 11 (compat/compat)
     Error    163,26: URL is not supported in IE 11 (compat/compat)

while having in package.json :

    "dependencies": {
        "babel-eslint": "^8.2.2",
        "browserslist": "^3.1.1",
        "eslint": "^4.18.2",
        "eslint-plugin-compat": "^2.2.0"
    },
    "browserslist": [
        "last 2 versions",
        "not < 0.25%",
        "not op_mini all",
        "not android 4.4.3"
    ],
    "eslintConfig": {
        "settings": {
            "polyfills": [
                "AbortController",
                "Array.from",
                "BroadcastChannel",
                "document.currentScript",
                "fetch",
                "intersectionobserver",
                "navigator.maxTouchPoints",
                "navigator.serviceWorker",
                "Object.assign",
                "Object.entries",
                "Object.values",
                "Promise",
                "Proxy",
                "Reflect",
                "URL",
                "URLSearchParams"
            ]
        }
    }

https://github.com/amilajack/eslint-plugin-compat/issues/242 might related issue.

**Comment by ljharb** [comment]
Does `npm ls` run successfully? If not, your dep graph is invalid, and you can't expect anything to work.

Prior to #242 being resolved, it is *invalid* to try to use eslint 6 with this project.

**Comment by laukstein** [comment]
Ignore this, repo packages where outdated. I succeed to update it with :

    ncu -u
    npm install

and now it seems working fine.

**Comment by laukstein** [comment]
@ljharb, `npm ls` shows

    npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0, required by eslint-plugin-compat@3.1.2

Any ETA to support on ESLint v6 ?

**Comment by amilajack** [comment]
https://github.com/amilajack/eslint-plugin-compat/pull/243#issuecomment-504709847
