### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by lukejagodzinski** [amilajack/eslint-plugin-compat#257]
From what I see this plugin only works with JS and despite the fact that the `@typescript-eslint/parser` parser produces eslint compatible tree. Is it something that is planned to be supported?

**Comment by lukejagodzinski** [comment]
Actually it works properly, my bad.

**Comment by panda0603** [comment]
Hello, how did you manage to get library with typescript? 
I got it working with js, but after installing "@typescript-eslint/eslint-plugin": "^3.9.0", and "@typescript-eslint/parser": "^3.9.0", I don't get lints for web compat anymore. 
Would be really helpful if you could share the settings.
Thanks!

**Comment by lukejagodzinski** [comment]
@panda0603 sorry to say but I don't have it anymore. From what I remember I've stopped using it because it wasn't as helpful as I guessed. I think the reason is that some rules can only be checked on runtime.
