### ISSUE TITLE
Remove schema restriction

### ISSUE THREAD

**Issue by bakkot** [amilajack/eslint-plugin-compat#263]
Currently it is impossible to configure the rule in eslint's config (as suggested [here](https://github.com/amilajack/eslint-plugin-compat/issues/125#issuecomment-480536329), for example), because the [`schema` property](https://github.com/amilajack/eslint-plugin-compat/blob/32c4f5833e33ccefe8003fa38a7ca9e415ae4539/src/rules/compat.js#L92) is set to forbid any options (see [eslint docs](https://eslint.org/docs/developer-guide/working-with-rules#options-schemas)).

Since [code tries to read from options](https://github.com/amilajack/eslint-plugin-compat/blob/32c4f5833e33ccefe8003fa38a7ca9e415ae4539/src/rules/compat.js#L100), that seems like a bug?

You can get around it by adding

```js
settings: {
  browsers: 'whatever',
}
```
to the top level eslint config, but it seems like it's intended that you be able to configure the rule directly.

**Comment by amilajack** [comment]
Fixed in https://github.com/amilajack/eslint-plugin-compat/pull/265
