### ISSUE TITLE
Break on browserslist query 'current node'

### ISSUE THREAD

**Issue by JounQin** [amilajack/eslint-plugin-compat#264]
```sh
TypeError: Error while loading rule 'compat/compat': Cannot read property '12.9.1' of undefined
```

Root issue: https://github.com/amilajack/eslint-plugin-compat/blob/master/src/providers/CanIUseProvider.js#L104

**Comment by jaydenseric** [comment]
This plugin crashes if the browserslist query contains any `node` (or variations like `Node`) related query, for example `Node >= 8.5`.

**Comment by FabianMeul** [comment]
I can confirm it crashes when targeting Node.

Any plans for fixing this? :-)

**Comment by amilajack** [comment]
This was published to the `next` tag. I'd love if everyone who had this issue can test out the new version:
```bash
npm install --save-dev eslint-plugin-compat@next
```
