### ISSUE TITLE
Ignore feature detection

### ISSUE THREAD

**Issue by kirly-af** [amilajack/eslint-plugin-compat#271]
We should have a way to do feature detection without disabling a rule.

A least one of theses examples should work with `"browserslist": ["cover 99.5%"]`:
```js
if (navigator.sendBeacon) {
}

if (navigator.sendBeacon != null) {
}

if (navigator.sendBeacon !== undefined) {
}

if (typeof navigator.sendBeacon !== 'undefined') {
}
```

**Comment by amilajack** [comment]
Duplicate of https://github.com/amilajack/eslint-plugin-compat/issues/26
