### ISSUE TITLE
Issue with functions not supported in IE11

### ISSUE THREAD

**Issue by SagarGupta1** [amilajack/eslint-plugin-compat#315]
Hi,
I used the plugin and configured the supported browser list to only support IE11. There are some functions like "includes" which is not supported in IE11. Still I was not seeing any eslint error. Kindly let me know if I need to do something extra.

**Comment by amilajack** [comment]
We can't check support for instance methods because ESLint doesn't provide type information for your code. We dont know if an object is an array or not. For more details, [see the type analysis doc](https://github.com/amilajack/eslint-plugin-compat/wiki/Ideas#type-analysis).
