### ISSUE TITLE
Dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jooohhn** [amilajack/eslint-plugin-compat#316]
The [Editor Configuration](https://github.com/amilajack/eslint-plugin-compat/blob/master/CONTRIBUTING.md#editor-configuration) leads to a non-existent section in [ERB](https://github.com/electron-react-boilerplate/electron-react-boilerplate#editor-configuration)

**Comment by amilajack** [comment]
Thanks for pointing this out. [I rewrote the doc](https://github.com/amilajack/eslint-plugin-compat/commit/eb1e07c2dcd8ce66e3c1566076e240e8c55bdf7c) to provide some better insights on how to onboard.
