### ISSUE TITLE
Adding pre-commit hooks

### ISSUE THREAD

**Issue by jooohhn** [amilajack/eslint-plugin-compat#317]
Adding [lint-staged](https://github.com/okonet/lint-staged) and [husky](https://github.com/typicode/husky) would help catch linting errors before entering CI. I can add this if you think it's a good idea

**Comment by ljharb** [comment]
I'd strongly discourage this - husky is dangerous, and has installed hooks into my company's private git repo before, unbidden. Git hooks are just fluff; it's much better to let CI do the gating.

**Comment by jooohhn** [comment]
@ljharb Could you elaborate on the danger of husky or git hooks? I tried googling `git hooks dangerous` and couldn't find explanations.

My current understanding is that there's nothing inherently dangerous about git hooks since they're scripts that run before an action - in this case, husky install a pre-commit linting hook.

Many popular JS repos also use git hooks. [Eslint](https://github.com/eslint/eslint/blob/master/package.json#L26) itself uses [Yorkie](https://github.com/yyx990803/yorkie) which is a fork of Husky with a few changes

Also, thanks for the feedback 😁

**Comment by ljharb** [comment]
They are inherently dangerous, which is why git itself won't let you provide git hooks as part of the repo - it's supposed to be an explicit opt-in by the user. "Just a script" means many things - a script can `rm -rf /`, or it can grab your credentials and send them somewhere, etc.

That many repos use them doesn't mean it's a good idea.

**Comment by jooohhn** [comment]
> That many repos use them doesn't mean it's a good idea.

Fair point. I mentioned this because an OS tool using husky may give reason for husky to be used in that tool's plugin.

> "Just a script" means many things - a script can rm -rf / , or it can grab your credentials and send them somewhere, etc.

Also fair, especially given prior npm security incidents. But I don't see a reason why husky should be strongly discouraged that couldn't be also applied to any popular OS tool in general.

Husky setting up `rm rf /` in a hook because of a poorly audited commit could happen just as `child_process.exec('rm -rf /')` on some other Node-based dependency.

**Comment by ljharb** [comment]
Sure, the issue is that the latter would occur when you use a dependency; the former could occur *without ever running your code at all*, merely when you run a git command. It's simply not worth the minor convenience of getting feedback prior to CI without running a command - you can run `npm test` in the CLI and get the same effect, without the danger.

**Comment by jooohhn** [comment]
> the issue is that the latter would occur when you use a dependency; the former could occur without ever running your code at all, merely when you run a git command.

In cases where changes are pushed without local running, I agree with your take on husky having no value. But it's not the general case for code to be modified without execution first (e.g. linting, testing, debugging).

And in that general case, husky vulnerabilities are applicable to any other npm dependency that is will be used when code is ran.

>  you can run `npm test` in the CLI and get the same effect, without the danger.

This alternative goes back to the prior point of development. If `npm test` is ran before commit, the local environment is exposed to dependency risks just as husky hooks would.

I don't believe it's concern with husky per-se, but rather the npm ecosystem as a whole.

**Comment by ljharb** [comment]
I think it's specifically bad with git hooks, because git operations are trusted by users in a way other ones aren't.
