### ISSUE TITLE
No check for Blob.arrayBuffer

### ISSUE THREAD

**Issue by wbobeirne** [amilajack/eslint-plugin-compat#320]
Not sure if this makes more sense here or in `compat-db`, but I just got burned by using [`Blob.arrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer) which is quite new and has terrible support.

**Comment by amilajack** [comment]
What browsers does it not work on?

**Comment by wbobeirne** [comment]
Compatibility chart is in the linked MDN article: https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer#Browser_compatibility
