### ISSUE TITLE
`window is not supported in IE Mobile 10`

### ISSUE THREAD

**Issue by brettz9** [amilajack/eslint-plugin-compat#322]
Is this for real?

Getting this upon recent updates... Feel free to close if this must be a dependency issue, and sorry haven't dug deeply, but this seemed a pretty shocking result if it were true...

(I have targets to 100% and am explicit with all polyfills.)

**Comment by amilajack** [comment]
Are you able to reproduce this with `eslint-plugin-compat@next`?

**Comment by brettz9** [comment]
Yes... 3.6.0-0

**Comment by brettz9** [comment]
FWIW, no difference with a fresh `node_modules` and `package-lock.json`

**Comment by amilajack** [comment]
Actually my mistake. I didnt push a new release to `@next` tag. This issue is fixed in https://github.com/amilajack/eslint-plugin-compat/pull/323

**Comment by amilajack** [comment]
This should be fixed in latest `next` tag now. Sorry for the confusion/

**Comment by brettz9** [comment]
No worries. No more message about `window`.

I am however now seeing: `history is not supported in IE 5.5` which I hadn't before. Though it sounds a little strange to me that the whole object , it at least sounds possible. Still, it might be worth looking into if you think there could be a new problem there. Thanks!

**Comment by ljharb** [comment]
Anything that enumerates the entire global will need to be very careful about avoiding properties that trigger deprecation warnings. See https://github.com/ljharb/object-keys/blob/master/implementation.js#L27-L78 for an example of some of the acrobatics needed.

**Comment by amilajack** [comment]
@brettz9 [History was added in IE 10](https://github.com/mdn/browser-compat-data/blob/master/api/History.json#L23)

**Comment by brettz9** [comment]
Ok, thanks, but I wonder though if the caniuse methods are for `pushState`, etc. Those were much more recent.

**Comment by amilajack** [comment]
Here's the [compat record for the IE pushstate API](https://github.com/mdn/browser-compat-data/blob/master/api/History.json#L264). Only supported versions are >= 10

**Comment by brettz9** [comment]
Ok, cool, thanks!
