### ISSUE TITLE
 document.querySelector() is not supported in IE 8

### ISSUE THREAD

**Issue by AlanBreck** [amilajack/eslint-plugin-compat#324]
I'm getting an error that `document.querySelector() is not supported in IE 8`, but according to MDN and [Can I Use](https://caniuse.com/#search=document.querySelector), it's partially supported in IE8:

> Partial support in IE8 is due to being limited to CSS 2.1 selectors and a small subset of CSS 3 selectors (see notes there). Additionally, it will have trouble with selectors including unrecognized tags (for example HTML5 ones).

**Comment by amilajack** [comment]
That is the expected behavior. The plugin warns about APIs that are not completely supported.

**Comment by AlanBreck** [comment]
Ahh. That makes sense. Is there a way to ignore specific method errors, then?

**Comment by amilajack** [comment]
You can add the error by [adding `document.querySelector` as a polyfill](https://github.com/amilajack/eslint-plugin-compat#v3).
