### ISSUE TITLE
Support ESLint v7

### ISSUE THREAD

**Issue by zypA13510** [amilajack/eslint-plugin-compat#325]
`eslint@7.0.0` was released. However, it is not supported by this plugin.

**Comment by amilajack** [comment]
How does the plugin not work with that version? Are there any errors?

**Comment by zypA13510** [comment]
At the very least, it is not listed as an acceptable version of peer dependency of this plugin. I assume you would also need to check the [list of breaking changes](https://eslint.org/docs/user-guide/migrating-to-7.0.0#breaking-changes-for-plugin-developers) to verify if anything needs to be changed.
