### ISSUE TITLE
question: what should be setting when using core-js v3

### ISSUE THREAD

**Issue by aladdin-add** [amilajack/eslint-plugin-compat#333]
we had imported `core-js` and `regenerator-runtime`
```js
import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

```js
// eslintrc.js
  "settings": {
    "polyfills": [
       ???
    ]
}
```

**Comment by amilajack** [comment]
In the npm `next` tag, all ES APIs will not be linted if you're using Babel or TS.

You can install the `next` tag like so:
```bash
yarn add --dev eslint-plugn-compat@next
npm install --save-dev eslint-plugn-compat@next
```
Let me know if this works for you!

**Comment by semiaddict** [comment]
Hi,

First thank you @amilajack for this great plugin.

I am, however, having trouble using this new feature with Babel and Webpack installed.
Looking at the code in https://github.com/amilajack/eslint-plugin-compat/pull/329/commits/db34a2eea38e9ab2312706acfd92dd66a5a197a9, it seems that the plugin is trying to detect 'babel' as a property of package.json, however I don't see how this property would be part of package.json. Am I missing something ?

At the moment I got it working by adding "es:all" to the polyfills list with eslint-plugin-compat@next.

In any case, it would be great to document how to ignore ES APIs, whether automatically (if babel is installed) or manually (by specifying "es:all" as a polyfill).

**Comment by ljharb** [comment]
Babel config goes in .babelrc, .babelrc.js, or a babel property in package.json.

**Comment by semiaddict** [comment]
> Babel config goes in .babelrc, .babelrc.js, or a babel property in package.json.

Ah. Didn't know it could be a property in package.json.
Thanks for the info.
