### ISSUE TITLE
Doesn't check navigator features that aren't supported by IE11

### ISSUE THREAD

**Issue by a00git** [amilajack/eslint-plugin-compat#354]
My browserslist is `[">0.25%", "IE 11", "not op_mini all"]` and when I try to use `navigator.clipboard.writeText` or `navigator.hardwareConcurrency` ([both](https://caniuse.com/#feat=hardwareconcurrency) [are](https://caniuse.com/#feat=mdn-api_clipboard_writetext) not supported by IE11) eslint doesn't rise an error

I guess you need to get info about `navigator` features in your `CanIUseProvider`

**Comment by amilajack** [comment]
Yes, this issue can be resolved by using caniuse records. We're using [MDN's compat data](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) for validation. The [mdn compat table](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) shows IE as `unknown`. This is an upstream issue but feel free to PR for adding those APIs to the caniuse provider. PR will be quickly merged.
