### ISSUE TITLE
Browser Targets not working

### ISSUE THREAD

**Issue by deecewan** [amilajack/eslint-plugin-compat#36]
Hey,

So, following the config provided in the `README.md`, I have `targets: ["chrome >= 50"]` in my `.eslintrc`.

When running the lint, however, I get 

```
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:103:47
    at Array.filter (native)
```

I put some logging in, and it seems that when I use `'chrome >= 50'` it dies (on any browser, specifying a version like that makes it die), but providing the raw browser name (`chrome` or `firefox`) makes the lint work.

.eslintrc settings:

```json
"settings": {
    "targets": [
      "chrome >= 50", "firefox", "edge", "safari >= 10"
    ],
    "compiler": "babel",
}
```

**Comment by amilajack** [comment]
See https://github.com/amilajack/eslint-plugin-compat/issues/24.

**Comment by amilajack** [comment]
You can temporarily use `eslint-plugin-compat@1.0.0-1`, which supports this:

```bash
npm i -D eslint-plugin-compat@1.0.0-1
```
