### ISSUE TITLE
Configuration to make library work with TypeScript

### ISSUE THREAD

**Issue by panda0603** [amilajack/eslint-plugin-compat#390]
Hello, 

First of all thanks for the library. 

After following the README, I got eslint to check for web compat successfully. 

However when I try to get lint working with typescript after installing "@typescript-eslint/eslint-plugin": "^3.9.0", "@typescript-eslint/parser": "^3.9.0", 

the lint for web compat does not appear anymore. Only ts lint is appearing. 

Following is my .eslintrc.json: 

```
{
  "env": {
    "browser": true,
    "es2020": true
  },
  "parser": "@typescript-eslint/parser",
  "extends": ["plugin:compat/recommended", "airbnb"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "plugins": ["react", "@typescript-eslint"],
  "rules": {}
}
```

and my package.json: 

```
{
  "name": "web-compat",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.0",
    "@typescript-eslint/parser": "^3.9.0",
    "eslint": "^7.6.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-plugin-compat": "^3.8.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.5",
    "eslint-plugin-react-hooks": "^4.0.8",
    "typescript": "^3.9.7"
  },
  "dependencies": {}
}

```

Any help appreciated.
Thanks!

**Comment by amilajack** [comment]
I was able to create a demo with TS with the same config:
https://github.com/amilajack/eslint-plugin-compat-typescript-demo

**Comment by panda0603** [comment]
@amilajack thanks! what if it has tsconfig.json file, does it still work then? Most of the time we have tsconfig file if we use typescript
