### ISSUE TITLE
browserslist lookup isn't relative to target file

### ISSUE THREAD

**Issue by Jessidhia** [amilajack/eslint-plugin-compat#42]
Ideally, it should behave similarly to the `.eslintrc` resolution. Right now it's relative to `process.cwd()`, which is not a nice place to be.

This can probably be helped by giving the path of the file being linted as the `path` option in the browserslist calls, e.g. `browserslist(undefined, { path: filePath })`

**Comment by amilajack** [comment]
@Kovensky Would appreciate a PR for this. I'm contributing to a related project at the moment and am short on time

**Comment by amilajack** [comment]
@ai can you confirm @Kovensky 's finding?

**Comment by ai** [comment]
Yeap. You need to pass `path` option to `browserslist` function call.

https://github.com/postcss/autoprefixer/blob/3de19bf91d0b175e3c8c8a42aa12d88d4fa344a3/lib/browsers.coffee#L27-L31

(you can ignore `env` and `stats` options, they are not popular and could be done with environment variables)

**Comment by amilajack** [comment]
@ai I'm not very familiar with coffeescript. Also are you referring to node's path module?

**Comment by ai** [comment]
@amilajack don’t worry. I just showed that Autoprefixer path a current file path as `path` option to `browserslist`.

**Comment by amilajack** [comment]
@Jessidhia @ai Finally pushed a fix for this in https://github.com/amilajack/eslint-plugin-compat/pull/217
