### ISSUE TITLE
Object spread syntax

### ISSUE THREAD

**Issue by JoshWhite** [amilajack/eslint-plugin-compat#454]
Is it possible to add support for this when the browsers specified support it?

```
const someObject = { myProp: 1 };

const someMergedObject = {
     ...someObject
}
```

Currently, if eslint's config has "env.es6: true", it will throw an invalid syntax error. 

I know I could update the parser options to `ecmaVersion: 2018`, but I'm worried that if some features in this ES version are not yet supported by the specified browser(s), I could unknowingly introduce a bug without the linter shouting.

**Comment by amilajack** [comment]
Language syntax additions can be transpiled and are therefore not a current priority for eslint-pluign-compat.
