### ISSUE TITLE
Compatibility with Visual Studio 2019

### ISSUE THREAD

**Issue by nheapsspreadco** [amilajack/eslint-plugin-compat#462]
Hi,

Please would you advise whether or not I should expect eslint-plugin-compat to work in Visual Studio?

(All the examples I have seen are for VS Code.)

I have npm installed eslint-plugin-compat in Visual Studio, and I have a browserlist section in my package.json ("since 2000", as a broad test), but ESLint is not highlighting browser features (e.g. fetch) I expect to be incompatible with my browser list.

Many thanks,

Nick

**Comment by amilajack** [comment]
It should work as long as you have eslint integration in VS
