### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Semigradsky** [amilajack/eslint-plugin-compat#477]
Master version has `@mdn/browser-compat-data` 3.x in dependencies.

But there is still 2.x in last published to npm version (eslint-plugin-compat@3.9.0).

**Comment by amilajack** [comment]
Thanks for the callout. I'll cut a release in a few hours.

**Comment by amilajack** [comment]
I cut an alpha release for https://github.com/amilajack/eslint-plugin-compat/releases/tag/v3.9.1-0. Feel free to test before I cut to latest tag

**Comment by Semigradsky** [comment]
@amilajack  I have tried alpha release on my projects, no new bugs. LGTM 👍

**Comment by Semigradsky** [comment]
Ha, looks like `eslint-plugin-compat` doesn't import `@mdn/browser-compat-data`.
I see that `ast-metadata-inferer` uses `mdn-browser-compat-data` for getting info from mdn. Can we switch to `@mdn/browser-compat-data`? https://github.com/amilajack/ast-metadata-inferer/issues/129
