### ISSUE TITLE
Support for ESLint 8?

### ISSUE THREAD

**Issue by zaygraveyard** [amilajack/eslint-plugin-compat#488]
Does this plugin support the newly released ESLint 8?
If so then version 8 should be added to the `peerDependencies`

**Comment by jakejarvis** [comment]
Working great for me, just the warning about an incorrect peer dependency :)

**Comment by marvinhagemeister** [comment]
@amilajack Just tried to install the prerelease but it looks like the `peerDependencies` field in `package.json` hasn't been updated.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: eslint-config-preact@1.2.0
npm ERR! Found: eslint@8.2.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from eslint-plugin-compat@4.0.0-0
```
