### ISSUE TITLE
`Intl.DisplayNames` rule from `@mdn/browser-compat-data` doesn't work

### ISSUE THREAD

**Issue by yurijmikhalevich** [amilajack/eslint-plugin-compat#524]
Hi @amilajack! 👋 

Here is [a modification of the `amilajack/eslint-plugin-compat-demo`](https://github.com/yurijmikhalevich/eslint-plugin-compat-demo) that demonstrates that the check doesn't work.

It should err when the user is using [`Intl.DisplayNames` and the `browserslist` is configured for `iOS 14`](https://caniuse.com/?search=Intl.DisplayNames):

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/4187729/187750533-6db78b28-7701-48ef-b7b2-03dcce2432f6.png">

There are probably other rules in `@mdn/browser-compat-data` that `eslint-plugin-compat` doesn't take advantage of. Is there any way I can help solve this?

**Comment by yurijmikhalevich** [comment]
I suspect that something preventing checks from the `es` group from executing: https://github.com/amilajack/ast-metadata-inferer/blob/6886ddd8d970a5e083f98743077cea73a01d14a9/src/providers/mdn/index.ts#L25-L31 🤔

**Comment by yurijmikhalevich** [comment]
Looks like the issue is in the outdated mdn-browser-compat used in ast-metadata-inferer. I submitted the PR with mdn/browser-compat-data update that fixes the issue: https://github.com/amilajack/ast-metadata-inferer/pull/145.

**Comment by yurijmikhalevich** [comment]
This PR https://github.com/amilajack/eslint-plugin-compat/pull/525 includes changes required to make everything work together.

**Comment by amilajack** [comment]
https://github.com/amilajack/ast-metadata-inferer/pull/145
