### ISSUE TITLE
Doesn't detect the use of DOM manipulation convenience methods

### ISSUE THREAD

**Issue by ColinEberhardt** [amilajack/eslint-plugin-compat#53]
I don't think this plugin detects the use of API methods such as ParentNode.append:

http://caniuse.com/#feat=dom-manip-convenience

Is there documentation that indicates what is and isn't detected? I'd certainly be interested in contributing to expand upon the current checks.

**Comment by amilajack** [comment]
This plugin isnt actually responsible for api compat lookups. I'm working on an database similar to caniuse. The database currently have around 15K API's, including CSS and JS API's'.

**Comment by amilajack** [comment]
Forgot to include the link to the database. Here it is:

https://github.com/amilajack/compat-db
