### ISSUE TITLE
Support for BROWSERSLIST_CONFIG?

### ISSUE THREAD

**Issue by darahak** [amilajack/eslint-plugin-compat#54]
Hello,

I was trying to use `eslint-plugin-compat` as a global plugin for projects that don't have `package.json` files.

I decided to define a `browserslist` file that I could reference through environment variable `BROWSERSLIST_CONFIG` as indicated [here](https://github.com/ai/browserslist#environment-variables), but it didn't seem to work: I saw no error from the plugin.

Is it working as expected?
Is it possible to add support for this use case? (I can try to make a PR if you agree)

Thanks.

**Comment by amilajack** [comment]
> Is it working as expected?
Is it possible to add support for this use case? (I can try to make a PR if you agree)

I didnt add support for that feature yet. Here's a relevant discussion:

https://github.com/amilajack/eslint-plugin-compat/issues/42#issuecomment-274727637

Also thanks in advance for the PR! 🎉🎉🎉 Would be great if you could add some tests along with the changes!

**Comment by darahak** [comment]
@amilajack I started looking at the code to figure out how to achieve this, and I have some questions if you don't mind (I never worked on ESLint plugins before).

In `compat.js:41`:
```js
    // Determine lowest targets from browserslist config, which reads user's
    // package.json config section. Use config from eslintrc for testing purposes
    const browserslistConfig: BrowserListConfig =
      context.settings.browsers ||
      context.settings.targets;
```
I understand the `context.settings` object is provided by [ESLint](http://eslint.org/docs/developer-guide/working-with-rules-new#the-context-object), but I don't see how we get `context.settings.browsers`. Also `context.settings.targets` doesn't have a Flow type declaration, so is it not used anymore?

I feel like this is only defined during tests and the `browserslist` config is actually fetched in `function DetermineTargetsFromConfig` from `Versioning.js`, but the comment above is not saying that so it's confusing. In this case, how do we get from `package.json`'s `browserslist` to `context.settings.browsers`?

**Comment by amilajack** [comment]
@darahak `context.settings.targets` and `context.settings.browsers` are the same thing. Initially this plugin worked by adding targets to the eslint config. I didn't want to force users to migrate to the browserslist config in package.json so I still allow configuration through the `eslintrc`. If `browserslistConfig` is undefined and no config is found in the `eslintrc`, [`DetermineTargetsFromConfig()` will use the browserslist config](https://github.com/amilajack/eslint-plugin-compat/blob/master/src/Versioning.js#L15)

**Comment by darahak** [comment]
Thanks for clarifying.

But then, my use case should have worked since [`browserslist()`](https://github.com/ai/browserslist/blob/master/index.js#L154) looks up `process.env.BROWSERSLIST` and `process.env.BROWSERSLIST_CONFIG`.

I'm missing something :thinking:

**Comment by amilajack** [comment]
I think you need to pass the env config to browserslist explicitly https://github.com/amilajack/eslint-plugin-compat/issues/42#issuecomment-274727637

**Comment by darahak** [comment]
@amilajack I just realized the first time I had this problem was in Atom, and it was probably not launched from the terminal which had defined `BROWSERSLIST_CONFIG`.

I just tried again, but I ran `eslint` directly from the terminal and had the expected results.

That's why I was struggling to understand how it could not work 😭
