### ISSUE TITLE
Please update `ast-metadata-inferer` to 0.8.x

### ISSUE THREAD

**Issue by Semigradsky** [amilajack/eslint-plugin-compat#547]
`ast-metadata-inferer` v0.7 uses `@mdn/browser-compat-data` v3.x
`ast-metadata-inferer` v0.8 uses `@mdn/browser-compat-data` v5.x

`eslint-plugin-compat` currently uses `@mdn/browser-compat-data` v5.x

**Comment by koddsson** [comment]
I believe this has been fixed by #561

**Comment by Semigradsky** [comment]
Great!
