### ISSUE TITLE
False positive: String.raw() is not supported in Opera 92

### ISSUE THREAD

**Issue by joeplaa** [amilajack/eslint-plugin-compat#548]
After upgrading from version 4.0.2 to 4.1.2 I get a warning: `String.raw() is not supported in Opera 92`.

However, [caniuse.com](https://caniuse.com/mdn-javascript_builtins_string_raw) reports it is supported since Opera 28. Same on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw#browser_compatibility).

**Comment by koddsson** [comment]
Try updating to the latest version? I'm not getting this error on `4.1.4`. Maybe you can provide a reproduction of this issue in a github repo if this is still happening for you on 4.1.4.

**Comment by joeplaa** [comment]
This is indeed fixed in `4.1.4`. Thanks.
