### ISSUE TITLE
Crash when browserslist is newer than caniuse-db

### ISSUE THREAD

**Issue by Kovensky** [amilajack/eslint-plugin-compat#58]
A new release of browserslist may produce, e.g., `chrome 56`, but the data in `caniuse-db` (or in the snapshot included in 1.0.1) does not include it if it is old enough.

This results in attempting to call `.includes('n')` on `undefined` instead of `string`, which is a crash.

**Comment by swernerx** [comment]
I see the same error when using Atom editor which is kind of frustrating with large error dialogs popping up regularly.

I figure the error in `CanIUseProvider` which seems be be fixed on GitHub. Could you @amilajack  please release the new version to npm?

**Comment by amilajack** [comment]
@swernerx definitely. Locking the versions should work.

`"browserslist": "1.7.0"` instead of `"browserslist": "^1.7.0"`

**Comment by amilajack** [comment]
Pushed npm prerelease `1.0.2-0`. Would be great if you guys could test to make sure this was resolved.

To make sure this doesn't happen in the future, i think we have to implement some kind of e2e tests for the npm package as a whole (maybe through npm link?). Any thoughts on how this can be done?

**Comment by swernerx** [comment]
Looks good for me in 1.0.2.
