### ISSUE TITLE
mdn browser definition is outdated

### ISSUE THREAD

**Issue by maxired** [amilajack/eslint-plugin-compat#610]
Hi,

is seems that the mdn browser definition is outdated and cannot be updated.
From what I understand, this code does not import directly `@mdn/browser-compat-data`, but uses `ast-metadata-inferer` as intermediate layer.

The issue is that `ast-metadata-inferer` is packages with it's own `compat.json` file, build at release time, with previous version of `@mdn/browser-compat-data`.
this means that upgrading `@mdn/browser-compat-data` locally does not solve the issue

**Comment by lapwingcloud** [comment]
seems like this is the reason causing the linter not reporting the Array `toReversed` `toSorted` `toSpliced` methods

**Comment by Merri** [comment]
Does this mean all browser features added after February 2023 are not being caught at the moment?

I was about to add `eslint-plugin-compat` to protect against a mistake I made (using `toSpliced`) but it does not catch it so I feel like the tool is not worth the added complexity for now.

**Comment by MattisAbrahamsson** [comment]
I opened a PR in `ast-metadata-inferer` [here](https://github.com/amilajack/ast-metadata-inferer/pull/165), let's hope it gets merged.

A plugin for linting browser supports should continually update the browser support information, otherwise what's the point

**Comment by cyrilf** [comment]
Hey,
Thanks for the collective effort on resolving this. :raised_hands: 
@amilajack thanks for your reactivity with the last commit :zap:
Can you release a new version `6.0.2`?

**Comment by amilajack** [comment]
I've updated ast-metadata-inferer and @mdn/browser-compat-data and published to 6.0.2.
