### ISSUE TITLE
[Wiki] Incorrect link to caniuse.com

### ISSUE THREAD

**Issue by darahak** [amilajack/eslint-plugin-compat#62]
On this [wiki page](https://github.com/amilajack/eslint-plugin-compat/wiki/Adding-polyfills), the link to `caniuse.com` points to https://github.com/amilajack/eslint-plugin-compat/wiki/caniuse.com instead of http://caniuse.com/

**Comment by amilajack** [comment]
Fixed! Thanks for this 🎉
