### ISSUE TITLE
Missing error

### ISSUE THREAD

**Issue by jpradelle** [amilajack/eslint-plugin-compat#72]
If I put IE9 in browser list and use ArrayBuffer I don't get any error, but ArrayBuffer is not available in IE 9: http://caniuse.com/#search=ArrayBuffer

**Comment by amilajack** [comment]
The number of APIs that this plugin supports is limited for the time being. I havent found a good way to determine the types of APIs, their properties, and compatibility. I'm working on [another project](https://github.com/amilajack/compat-db) that provides the necessary information for this plugin to work for almost any API. It supports roughly 6K API's

**Comment by hirokiosame** [comment]
Any updates on this @amilajack ?

**Comment by ericmasiello** [comment]
Same here

**Comment by MingXingTeam** [comment]
Now,  Can i use compat-db?
