### ISSUE TITLE
Check dependencies

### ISSUE THREAD

**Issue by Yamakaky** [amilajack/eslint-plugin-compat#73]
Is there a way to check if the dependencies of the application respect the compatibility specifications? Even if it's only one time and not at each build.

**Comment by amilajack** [comment]
There isnt a way to do this yet. Will work on a project that does this

**Comment by amilajack** [comment]
@Yamakaky On second thought, there is a way but its not very elegant or practical. You can tell configure eslint to lint all of your `node_modules` with only the `compat` rule enabled. This is a terrible solution and don't recommend it.

**Comment by Yamakaky** [comment]
^^ Maybe with a separate config file just for this use case?

**Comment by amilajack** [comment]
I think you should be able to use just npm scripts and cli commands

**Comment by Yamakaky** [comment]
`eslint --env browser --plugin compat --rule "compat/compat:2" --no-eslintrc --no-ignore node_modules/**/*.js` seems to do the job.
