### ISSUE TITLE
Running in CI

### ISSUE THREAD

**Issue by Dima4ka** [amilajack/eslint-plugin-compat#74]
I have looked through the READMEs and one thing remains unclear to me.

If I have a number of JS files in a project, can I run your tool on them and get a status code 0 if my target browsers fully support my JS and non-zero code otherwise?

I would love to have it as one of the tests in CI.

**Comment by amilajack** [comment]
If you run eslint as an npm scripts (or globally) then you will get an exit code of 0 if everything is supported. Look into eslint's cli. See the [demo here](https://github.com/amilajack/eslint-plugin-compat-demo/blob/master/package.json#L11)
