### ISSUE TITLE
`fetch` (and others?) is not throwing an error in certain old browser versions

### ISSUE THREAD

**Issue by happycollision** [amilajack/eslint-plugin-compat#75]
I am not sure how deep this problem goes, but here is an easy way to reproduce the symptom:

1. Clone the [eslint-plugin-compat-demo](https://github.com/amilajack/eslint-plugin-compat-demo)
2. Remove the `fetch` polyfill support from the `.eslintrc` file.
3. Change `browserslist` to `["Chrome 49"]`.

Upon reloading the `App.js` file, you would now expect three red dots in Atom. Instead, there are still only two.

![compat fail](https://cloud.githubusercontent.com/assets/3663628/25013072/f9901070-2037-11e7-86d7-a78a480e29ef.png)

I do not know how many Javascript APIs this problem affects (I *happened* to use `fetch` to test my setup) and I do not know which browser queries cause this issue (I *happened* to try Chrome 49 because I am testing for Windows XP support in my project).

**Comment by happycollision** [comment]
FYI: my setup is correct. Here is a screenshot after I change `broswerslist` to `["last 2 versions"]`

![compat win](https://cloud.githubusercontent.com/assets/3663628/25013206/5eeee04a-2038-11e7-97a7-12ce51d889cf.png)

**Comment by darahak** [comment]
I don't see a problem.
Fetch support started on Chrome 42 according to [caniuse](http://caniuse.com/#feat=fetch) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility).

**Comment by happycollision** [comment]
Oh. My. Goodness.

Silly of me.
