### ISSUE TITLE
Kangax table implementation?

### ISSUE THREAD

**Issue by Munter** [amilajack/eslint-plugin-compat#77]
The readme shows that Kangax compatibility tables are taken into account in this plugin, but I get no warnings when I configure `browserslist: ['ie 10']` and use `Object.assign()` for example

Is this a bug or am I using it wrong?

**Comment by amilajack** [comment]
See [this comment](https://github.com/amilajack/eslint-plugin-compat/issues/72#issuecomment-288834016). Adding kangax table support is also in the roadmap but this will take time.

**Comment by replete** [comment]
Ahh, I thought this was happening because of the *Goals* section in `README.md` being ticked. Might want to fix that.

I'll pull this later on and contribute, great work dude!
