### ISSUE TITLE
Element.closest() on IE11

### ISSUE THREAD

**Issue by m1n0s** [amilajack/eslint-plugin-compat#78]
Hi @amilajack! Seems like your plugin don't catch very common mistake for IE11 about not supporting of `Element.closest()`.
This line has no errors for IE11 config:

`const foo = documect.querySelector('.bar').closest('.baz');`

But it's presented here - http://caniuse.com/#feat=element-closest

Same for `NodeList#forEach` in IE11 but actually I can't find it on caniuse.

P.S. To prove that config is working right:
![image](https://cloud.githubusercontent.com/assets/12004923/25771056/3fe08a04-324f-11e7-80fd-1f3659c8376e.png)

**Comment by amilajack** [comment]
See [this comment](https://github.com/amilajack/eslint-plugin-compat/issues/72#issuecomment-288834016)
