### ISSUE TITLE
Use Browserslist 2

### ISSUE THREAD

**Issue by ai** [amilajack/eslint-plugin-compat#82]
We released Browserslist 2 with ([full changelog with our reasons](https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released)):

1. Better performance because of caching
2. It depends on `caniuse-lite` (1 MB) instead of `caniuse-db` (7 MB)
3. Now `last n versions` contains all browsers

Unfortunately, this changes requires major update for this tool too. But all this changes are important and will not have problems for most of users. As people told on conferences — don’t afraid major releases, just make changes smaller — it is best example.

We already released Autoprefixer 7 and doiuse 3 with new Browserslist. It is important for community to have same Browserslist version (especially because of different `last n versions` behaviour).

@amilajack can you release 2.0 with new Browserslist soon?

**Comment by amilajack** [comment]
@ai sure thing! I'll definitely PR for this sometime soon.

**Comment by ismay** [comment]
Fixing this will also close #80

**Comment by ai** [comment]
If you need help, just tell me. I will send you developers from cultofmartians.com

**Comment by ai** [comment]
I think it is connected too https://github.com/amilajack/eslint-plugin-compat/issues/85

(`caniuse-db` and `caniuse-lite` in dependencies is the worst scenario)

**Comment by amilajack** [comment]
Closed by https://github.com/amilajack/eslint-plugin-compat/pull/83

**Comment by ai** [comment]
Awesome. Thanks!

Don’t forget about `caniuse-lite` migration. It should be done in same release with Browserslist 2, or `node_modules` will become even bigger :).
