### ISSUE TITLE
String methods compatibility.

### ISSUE THREAD

**Issue by virus-warnning** [amilajack/eslint-plugin-compat#84]
Cannot lint some string methods correctlly.

Methods | IE Compatibility
---- | ----
String.endsWith() |  IE didn't support
String.normalize() | IE didn't support
String.includes() | IE didn't support
String.localeCompare() | IE11
String.repeat() | IE didn't support
String.startsWith() | IE didn't support
String.trimLeft() | not standard
String.trimRight() | not standard

[MDN - String.prototype.endsWith()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)

**Comment by brenthargrave** [comment]
@virus-warnning You might recast this issue to include support for MDN data *generally*.
For example, IE lacks support for `Array.findIndex`, [per MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Browser_compatibility).
It'd be great if `compat` caught these gaps too!

How could we go about including MDN's data?

**Comment by ianwalter** [comment]
@brenthargrave caniuse reports that `string.includes` (and `array.includes`)  is not supported in IE, but the compat plugin still doesn't seem to throw an error for those.

**Comment by Katona** [comment]
It seems the plugin checks for specific expressions only, they are listed in https://github.com/amilajack/eslint-plugin-compat/blob/master/src/providers/CanIUseProvider.js. As for the database, it may be possible to create a provider which would use [the MDN compatibility database](https://github.com/mdn/browser-compat-data/).

**Comment by wzpan** [comment]
+1. We recently came across such incompatibility issue in our project for using `String.includes()` function. Hope `compat` can throw an error too.

**Comment by amilajack** [comment]
This plugin does not support instance methods at the moment. See https://github.com/amilajack/eslint-plugin-compat/issues/168#issuecomment-462009281
