### ISSUE TITLE
Use caniuse-lite

### ISSUE THREAD

**Issue by ai** [amilajack/eslint-plugin-compat#85]
We loved `caniuse-db`, but it uses 7 MB and contains many irrelevant data.

This is why @ben-eb created [`caniuse-lite`](https://github.com/ben-eb/caniuse-lite). It is just a copy of latest `caniuse-db` (he wrote autorelease script) with less data and better compression. Only 1 MB.

Autoprefixer and Browserslist moved to `caniuse-lite`. So let’s use it here too. It is very easy, API is the same.

**Comment by amilajack** [comment]
Somewhat reluctant to depend on a dependency that doesn't have any tests. Maybe we could use it after it adds some tests?

**Comment by ai** [comment]
Sure, adding tests to `caniuse-lite` will be great.

**Comment by amilajack** [comment]
@ai it's been some time since this ticket was filed and it looks like the project has matured more since I initially looked at it. Would you like to PR for this?

**Comment by ai** [comment]
`caniuse-lite` now has tests https://github.com/ben-eb/caniuse-lite/blob/master/src/agents.test.js

Also, `caniuse-lite` is 2x time more popular than `caniuse-db` https://www.npmtrends.com/caniuse-lite-vs-caniuse-db

**Comment by amilajack** [comment]
Awesome! Would you be interested in putting together a PR for this?

**Comment by amilajack** [comment]
Awesome! Would you be interested in putting together a PR for this?

**Comment by ai** [comment]
Not in the next few weeks, sorry. Need to finish docs for my another open source project.
