### ISSUE TITLE
Didn't pick up Array.find incompatibility for IE10

### ISSUE THREAD

**Issue by jeznag** [amilajack/eslint-plugin-compat#93]
.eslintrc:
```
"rules": {
   "compat/compat": 2
 },
"env": {
    "browser": true,
    "jest/globals": true,
    "jest": true
  },
  "parser": "babel-eslint",
  "plugins": [
    "jest",
    "flowtype",
    "compat",
  ]
```

package.json:
```
"browserslist": [
    "IE 10"
  ]
```

Code:
`const answerForThisTimePeriod = this.state.answer.find((answer: TimeRangesAnswerType) => answer.timePeriod === timePeriod);`

Result:
No errors

**Comment by thekip** [comment]
I think it's just really hard to understand via static analysis that you call Array methods in that case. 
Because `this.state.answer` can be any of type, (for example predefined by your type with method .find())

**Comment by amilajack** [comment]
See https://github.com/amilajack/eslint-plugin-compat/issues/72#issuecomment-288834016

**Comment by amilajack** [comment]
This plugin does not support instance methods at the moment. See https://github.com/amilajack/eslint-plugin-compat/issues/168#issuecomment-462009281
